package com.handler.bot.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PositionData {
    private String buyAmt;
    private String cfSellAmt;
    private String prod;
    private String exSeg;
    private String sqrFlg;
    private String actId;
    private String cfBuyQty;
    private String hsUpTm;
    private String cfSellQty;
    private String tok;
    private String flBuyQty;
    private String flSellQty;
    private String sellAmt;
    private String posFlg;
    private String cfBuyAmt;
    private String stkPrc;
    private String trdSym;
    private String sym;
    private String multiplier;
    private String precision;
    private String expDt;
    private String type;
    private String genNum;
    private String series;
    private String prcNum;
    private String genDen;
    private int brdLtQty;
    private String exp;
    private String lotSz;
    private String optTp;
    private String prcDen;

    // Getters and setters for all fields
    // ... (omitted for brevity, will be generated by IDE or Lombok in real projects)

    public String getBuyAmt() { return buyAmt; }
    public void setBuyAmt(String buyAmt) { this.buyAmt = buyAmt; }
    public String getCfSellAmt() { return cfSellAmt; }
    public void setCfSellAmt(String cfSellAmt) { this.cfSellAmt = cfSellAmt; }
    public String getProd() { return prod; }
    public void setProd(String prod) { this.prod = prod; }
    public String getExSeg() { return exSeg; }
    public void setExSeg(String exSeg) { this.exSeg = exSeg; }
    public String getSqrFlg() { return sqrFlg; }
    public void setSqrFlg(String sqrFlg) { this.sqrFlg = sqrFlg; }
    public String getActId() { return actId; }
    public void setActId(String actId) { this.actId = actId; }
    public String getCfBuyQty() { return cfBuyQty; }
    public void setCfBuyQty(String cfBuyQty) { this.cfBuyQty = cfBuyQty; }
    public String getHsUpTm() { return hsUpTm; }
    public void setHsUpTm(String hsUpTm) { this.hsUpTm = hsUpTm; }
    public String getCfSellQty() { return cfSellQty; }
    public void setCfSellQty(String cfSellQty) { this.cfSellQty = cfSellQty; }
    public String getTok() { return tok; }
    public void setTok(String tok) { this.tok = tok; }
    public String getFlBuyQty() { return flBuyQty; }
    public void setFlBuyQty(String flBuyQty) { this.flBuyQty = flBuyQty; }
    public String getFlSellQty() { return flSellQty; }
    public void setFlSellQty(String flSellQty) { this.flSellQty = flSellQty; }
    public String getSellAmt() { return sellAmt; }
    public void setSellAmt(String sellAmt) { this.sellAmt = sellAmt; }
    public String getPosFlg() { return posFlg; }
    public void setPosFlg(String posFlg) { this.posFlg = posFlg; }
    public String getCfBuyAmt() { return cfBuyAmt; }
    public void setCfBuyAmt(String cfBuyAmt) { this.cfBuyAmt = cfBuyAmt; }
    public String getStkPrc() { return stkPrc; }
    public void setStkPrc(String stkPrc) { this.stkPrc = stkPrc; }
    public String getTrdSym() { return trdSym; }
    public void setTrdSym(String trdSym) { this.trdSym = trdSym; }
    public String getSym() { return sym; }
    public void setSym(String sym) { this.sym = sym; }
    public String getMultiplier() { return multiplier; }
    public void setMultiplier(String multiplier) { this.multiplier = multiplier; }
    public String getPrecision() { return precision; }
    public void setPrecision(String precision) { this.precision = precision; }
    public String getExpDt() { return expDt; }
    public void setExpDt(String expDt) { this.expDt = expDt; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public String getGenNum() { return genNum; }
    public void setGenNum(String genNum) { this.genNum = genNum; }
    public String getSeries() { return series; }
    public void setSeries(String series) { this.series = series; }
    public String getPrcNum() { return prcNum; }
    public void setPrcNum(String prcNum) { this.prcNum = prcNum; }
    public String getGenDen() { return genDen; }
    public void setGenDen(String genDen) { this.genDen = genDen; }
    public int getBrdLtQty() { return brdLtQty; }
    public void setBrdLtQty(int brdLtQty) { this.brdLtQty = brdLtQty; }
    public String getExp() { return exp; }
    public void setExp(String exp) { this.exp = exp; }
    public String getLotSz() { return lotSz; }
    public void setLotSz(String lotSz) { this.lotSz = lotSz; }
    public String getOptTp() { return optTp; }
    public void setOptTp(String optTp) { this.optTp = optTp; }
    public String getPrcDen() { return prcDen; }
    public void setPrcDen(String prcDen) { this.prcDen = prcDen; }
}
